# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec025690eeaf5584430709ce70e577ebc2f1b21434d95a14a8bc7ae8da21359b0371607e9bee8689f43a834e55e3cf3f42fcb5306de34e08753775723d7b9cc4

test:
  secret_key_base: 3ee6460e83c1a3f23580806ad4e67c5e151cad22b9bfb5100a2f5de8930c907e52ef3eaefdb0fc09e6a0906582052fda1a3109f1a9edd340c57bc1203e47443d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
